#!/bin/sh

xrandr --output eDP-1 --dpi 192

setxkbmap gb # keyboard layout

# trackpad input
TOUCHPAD_ID=$(xinput list | grep -i "touchpad" | grep -oG "id=[0-9]*" | grep -oG "[0-9]*")
xinput set-prop $TOUCHPAD_ID "libinput Tapping Enabled" 1

xinput set-prop $TOUCHPAD_ID "libinput Natural Scrolling Enabled" 1

xinput set-prop $TOUCHPAD_ID "libinput Middle Emulation Enabled" 1

xinput set-prop $TOUCHPAD_ID "libinput Disable While Typing Enabled" 0

# scaling
export QT_AUTO_SCREEN_SET_FACTOR=0
export QT_SCALE_FACTOR=2
export QT_FONT_DPI=96

export GDK_SCALE=2
export GDK_DPI_SCALE=0.5
